version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-vue
    working_dir: /hello-vue
    volumes:
      - ./hello-vue:/hello-vue
    ports:
      - "5173:5173"
